### PR TITLE
Update unmark.scss

### PR DESCRIPTION
**Pull request by simonschaufi**
Empty area should not be linked, only the link itself

### CODE REVIEW

**Comment by simonschaufi** [comment]
please execute grunt for me or is this done automatically after merge?

**Comment by williamknauss** [comment]
@cdevroe this seems like your area? Should this be merged?

**Comment by cdevroe** [comment]
@simonschaufi I'll have to pull and test this locally myself. What is it that you're attempting to do here?

**Comment by simonschaufi** [comment]
on the right side of the link is whitespace which is also linked. i think this is bad usability since there is a link where there is nothing. clicking this whitespace after my patch will open the sidebar instead of the link which is the expected behavior imho.

**Comment by cdevroe** [comment]
@simonschaufi Good catch. I like this. I'll see if we can get it merged in quickly.

**Comment by simonschaufi** [comment]
@cdevroe: what's the status here?

**Comment by cdevroe** [comment]
@simonschaufi Thanks for the reminder... I'll set aside time this week to roll it in.

**Comment by simonschaufi** [comment]
you closed this pull request without merge. why?

**Comment by cdevroe** [comment]
@simonschaufi Look at version 1.8. We're redesigning Unmark and this is already rolled into that.

**Comment by cdevroe** [comment]
@simonschaufi You can pull this branch, run grunt, and you'll see : https://github.com/plainmade/unmark/tree/proposals/version-1.8

**Pull request closed without merging**
